version: '3.1'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloud_project
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      DEVELOPER_MODE: true
      DB: "mongodb://root:password1@mongo:27017"
      HOST: http://localhost:8080
      SMTP_SERVER: smtp
      SMTP_PORT: 1025
      SMTP_AUTH_LOGIN: coolapp
      SMTP_AUTH_PASS: coolapppwd
    depends_on:
      - mongo
      - smtp
    
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password1
    ports:
      - 27017:27017


  smtp:
    image: mailhog/mailhog 
    restart: always
    container_name: mailhog
    ports: 
      - 1025:1025 
      - 8025:8025